# Generated by Django 5.2.4 on 2025-08-03 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnr_number', models.CharField(blank=True, max_length=50)),
                ('petitioner_name', models.CharField(blank=True, max_length=200)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, max_length=100)),
                ('court_hall', models.CharField(blank=True, max_length=50)),
                ('judge_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaseQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50)),
                ('filing_year', models.CharField(max_length=4)),
                ('user_ip', models.GenericIPAddressField()),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-queried_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField()),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('downloaded', models.BooleanField(default=False)),
                ('local_file_path', models.CharField(blank=True, max_length=500)),
                ('case_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.casedetail')),
            ],
            options={
                'ordering': ['-document_date'],
            },
        ),
        migrations.AddField(
            model_name='casedetail',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.casequery'),
        ),
        migrations.AddField(
            model_name='casequery',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casetype'),
        ),
        migrations.AddField(
            model_name='casetype',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.court'),
        ),
        migrations.AddField(
            model_name='casequery',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.court'),
        ),
    ]
